version: '3'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis

#  задел на тестирование
#  test:
#    build: .
#    command: pytest
#    depends_on:
#      - app
#      - redis